use_frameworks!

platform :ios, '8.0'

target 'common_ios_Example' do
  pod 'common_ios', :path => '../'

  target 'common_ios_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
